[package]
name = "rust-sockets"
version = "0.1.0"
authors = ["Dilip Kr. Shukla <contact@fusionstrings.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tungstenite = "*"